name: Firebase Notifications

on:
  schedule:
    - cron: "0 18 * * *"

jobs:
  readme-update:
    name: Send notifications
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          repository: RubenDeveloperJob/Cangur
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: database

      - name: Install packages
        run: pip install firebase_admin
        shell: sh

      - name: Run script
        run: python notifications/firebase-notifications.py
        shell: sh
